services:
  wazuh.seeder:
    build: ./seeder
    image: soc-lab/wazuh-seeder:1.0
    hostname: wazuh.seeder
    restart: "no"
    environment:
      - INDEXER_URL=https://wazuh.indexer:9200
      - INDEXER_USERNAME=admin
      - INDEXER_PASSWORD=SecretPassword
      - WAIT_FOR_TEMPLATE=false
    depends_on:
      - wazuh.indexer
